package com.logreposit.logrepositapi.communication.messaging.common;

public enum MessageType
{
    EVENT_CMI_LOGDATA_RECEIVED,
    EVENT_BMV_600_LOGDATA_RECEIVED,
    EVENT_LACROSSE_TX_LOGDATA_RECEIVED,
    EVENT_SOLARLOG_LOGDATA_RECEIVED,
    EVENT_FROELING_LAMBDATRONIC_S3200_LOGDATA_RECEIVED,
    EVENT_COTEK_SP_SERIES_LOGDATA_RECEIVED,
    EVENT_CCS811_LOGDATA_RECEIVED,
    EVENT_DHT_LOGDATA_RECEIVED,
    EVENT_GENERIC_LOGDATA_RECEIVED,
    // EVENT_LOGDATA_RECEIVED,
    EVENT_USER_CREATED,
    EVENT_USER_PASSWORD_CHANGED,
    EVENT_DEVICE_CREATED
}
